# Generated by Django 4.2.5 on 2023-10-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrestauApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='ordered_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='start_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
