# Generated by Django 4.2.5 on 2023-10-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrestauApp', '0004_table_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='end_datetime',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='meal',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
