# Generated by Django 4.2.5 on 2023-10-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrestauApp', '0005_alter_meal_end_datetime_alter_meal_start_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
