# Generated by Django 4.2.5 on 2023-10-04 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrestauApp', '0006_alter_meal_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qrestauApp.meal'),
        ),
    ]
