# Generated by Django 4.2.5 on 2023-10-04 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrestauApp', '0009_alter_mealitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='qrestauApp.item'),
            preserve_default=False,
        ),
    ]
