# Generated by Django 4.2.5 on 2023-10-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrestauApp', '0010_mealitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='password',
            field=models.CharField(db_index=True, default='passpass', max_length=255),
            preserve_default=False,
        ),
    ]
