# Generated by Django 4.2.5 on 2023-10-04 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qrestauApp', '0012_meal_anonymous_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='anonymous_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
